apiVersion: v1
kind: Pod
metadata:
  name: qemu-proxy
  labels:
    app: qemu-proxy
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: qemu-proxy
    image: fabiand/qemu-proxy
    securityContext:
      privileged: true
      runAsUser: 0
    env:
    - name: MODE
      value: proxy
---
kind: Service
apiVersion: v1
metadata:
  name: qemu-proxy-date
spec:
  selector:
    app: qemu-proxy
  ports:
  - protocol: TCP
    port: 80
