apiVersion: v1
kind: Pod
metadata:
  name: qemu-proxy
  labels:
    app: qemu-proxy
spec:
  securityContext:
    runAsUser: 0
#  volumes:
#      - name: host-dev
#        hostPath:
#          path: /dev
#      - name: host-sys
#        hostPath:
#          path: /sys
  containers:
  - name: qemu-proxy
    image: fabiand/qemu-proxy
    securityContext:
      privileged: true
      runAsUser: 0
#    volumeMounts:
#      - mountPath: /host-dev
#        name: host-dev
#      - mountPath: /host-sys
#        name: host-sys
---
kind: Service
apiVersion: v1
metadata:
  name: qemu-proxy-date
spec:
  selector:
    app: qemu-proxy
  ports:
  - protocol: TCP
    port: 80
